export interface Country {
  code: string;
  name: string;
}

export const COUNTRIES: Country[] = [
  { code: "AL", name: "Albânia" },
  { code: "DZ", name: "Argélia" },
  { code: "AD", name: "Andorra" },
  { code: "AO", name: "Angola" },
  { code: "AR", name: "Argentina" },
  { code: "AM", name: "Arménia" },
  { code: "AU", name: "Austrália" },
  { code: "AT", name: "Áustria" },
  { code: "AZ", name: "Azerbaijão" },
  { code: "BH", name: "Bahrein" },
  { code: "BD", name: "Bangladesh" },
  { code: "BE", name: "Bélgica" },
  { code: "BO", name: "Bolívia" },
  { code: "BA", name: "Bósnia e Herzegovina" },
  { code: "BR", name: "Brasil" },
  { code: "BG", name: "Bulgária" },
  { code: "CM", name: "Camarões" },
  { code: "CA", name: "Canadá" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "China" },
  { code: "CO", name: "Colômbia" },
  { code: "CD", name: "Congo" },
  { code: "CR", name: "Costa Rica" },
  { code: "CI", name: "Costa do Marfim" },
  { code: "HR", name: "Croácia" },
  { code: "CU", name: "Cuba" },
  { code: "CZ", name: "República Checa" },
  { code: "DK", name: "Dinamarca" },
  { code: "EC", name: "Equador" },
  { code: "EG", name: "Egito" },
  { code: "SV", name: "El Salvador" },
  { code: "EN", name: "Inglaterra" },
  { code: "EE", name: "Estónia" },
  { code: "ET", name: "Etiópia" },
  { code: "FI", name: "Finlândia" },
  { code: "FR", name: "França" },
  { code: "GA", name: "Gabão" },
  { code: "GE", name: "Geórgia" },
  { code: "DE", name: "Alemanha" },
  { code: "GH", name: "Gana" },
  { code: "GR", name: "Grécia" },
  { code: "GT", name: "Guatemala" },
  { code: "GN", name: "Guiné" },
  { code: "HN", name: "Honduras" },
  { code: "HU", name: "Hungria" },
  { code: "IS", name: "Islândia" },
  { code: "IN", name: "Índia" },
  { code: "ID", name: "Indonésia" },
  { code: "IR", name: "Irão" },
  { code: "IQ", name: "Iraque" },
  { code: "IE", name: "Irlanda" },
  { code: "IL", name: "Israel" },
  { code: "IT", name: "Itália" },
  { code: "JM", name: "Jamaica" },
  { code: "JP", name: "Japão" },
  { code: "JO", name: "Jordânia" },
  { code: "KZ", name: "Cazaquistão" },
  { code: "KE", name: "Quénia" },
  { code: "KR", name: "Coreia do Sul" },
  { code: "KW", name: "Kuwait" },
  { code: "LV", name: "Letónia" },
  { code: "LB", name: "Líbano" },
  { code: "LY", name: "Líbia" },
  { code: "LT", name: "Lituânia" },
  { code: "LU", name: "Luxemburgo" },
  { code: "MK", name: "Macedónia do Norte" },
  { code: "MG", name: "Madagáscar" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malta" },
  { code: "MX", name: "México" },
  { code: "MD", name: "Moldávia" },
  { code: "ME", name: "Montenegro" },
  { code: "MA", name: "Marrocos" },
  { code: "MZ", name: "Moçambique" },
  { code: "NL", name: "Holanda" },
  { code: "NZ", name: "Nova Zelândia" },
  { code: "NI", name: "Nicarágua" },
  { code: "NG", name: "Nigéria" },
  { code: "NO", name: "Noruega" },
  { code: "OM", name: "Omã" },
  { code: "PK", name: "Paquistão" },
  { code: "PA", name: "Panamá" },
  { code: "PY", name: "Paraguai" },
  { code: "PE", name: "Peru" },
  { code: "PH", name: "Filipinas" },
  { code: "PL", name: "Polónia" },
  { code: "PT", name: "Portugal" },
  { code: "QA", name: "Qatar" },
  { code: "RO", name: "Roménia" },
  { code: "RU", name: "Rússia" },
  { code: "SA", name: "Arábia Saudita" },
  { code: "SN", name: "Senegal" },
  { code: "RS", name: "Sérvia" },
  { code: "SK", name: "Eslováquia" },
  { code: "SI", name: "Eslovénia" },
  { code: "SO", name: "Somália" },
  { code: "ZA", name: "África do Sul" },
  { code: "ES", name: "Espanha" },
  { code: "SE", name: "Suécia" },
  { code: "CH", name: "Suíça" },
  { code: "SY", name: "Síria" },
  { code: "TW", name: "Taiwan" },
  { code: "TZ", name: "Tanzânia" },
  { code: "TH", name: "Tailândia" },
  { code: "TN", name: "Tunísia" },
  { code: "TR", name: "Turquia" },
  { code: "UG", name: "Uganda" },
  { code: "UA", name: "Ucrânia" },
  { code: "AE", name: "Emirados Árabes" },
  { code: "GB", name: "Reino Unido" },
  { code: "US", name: "Estados Unidos" },
  { code: "UY", name: "Uruguai" },
  { code: "VE", name: "Venezuela" },
  { code: "VN", name: "Vietname" },
  { code: "YE", name: "Iémen" },
  { code: "ZM", name: "Zâmbia" },
  { code: "ZW", name: "Zimbabué" },
].sort((a, b) => a.name.localeCompare(b.name, "pt"));

export function getCountryByCode(code: string | null | undefined): Country | undefined {
  if (!code) return undefined;
  return COUNTRIES.find((c) => c.code === code);
}
