// Names must match backend clubs.service.ts exactly
export const CLUBS_BY_LEAGUE: Record<string, string[]> = {
  // ===== ENGLAND =====
  'Premier League': [
    'Arsenal',
    'Aston Villa',
    'AFC Bournemouth',
    'Brentford',
    'Brighton & Hove Albion',
    'Burnley',
    'Chelsea',
    'Crystal Palace',
    'Everton',
    'Fulham',
    'Leeds United',
    'Liverpool',
    'Manchester City',
    'Manchester United',
    'Newcastle United',
    'Nottingham Forest',
    'Sunderland',
    'Tottenham Hotspur',
    'West Ham United',
    'Wolverhampton Wanderers',
  ],
  'EFL Championship': [
    'Birmingham City',
    'Blackburn Rovers',
    'Bristol City',
    'Charlton Athletic',
    'Coventry City',
    'Derby County',
    'Hull City',
    'Ipswich Town',
    'Leicester City',
    'Middlesbrough',
    'Millwall',
    'Norwich City',
    'Oxford United',
    'Portsmouth',
    'Preston North End',
    'Queens Park Rangers',
    'Sheffield United',
    'Sheffield Wednesday',
    'Southampton',
    'Stoke City',
    'Swansea City',
    'Watford',
    'West Bromwich Albion',
    'Wrexham',
  ],
  'EFL League One': [
    'AFC Wimbledon',
    'Barnsley',
    'Blackpool',
    'Bolton Wanderers',
    'Bradford City',
    'Burton Albion',
    'Cardiff City',
    'Doncaster Rovers',
    'Exeter City',
    'Huddersfield Town',
    'Leyton Orient',
    'Lincoln City',
    'Luton Town',
    'Mansfield Town',
    'Northampton Town',
    'Peterborough United',
    'Plymouth Argyle',
    'Port Vale',
    'Reading',
    'Rotherham United',
    'Stevenage',
    'Stockport County',
    'Wigan Athletic',
    'Wycombe Wanderers',
  ],
  'EFL League Two': [
    'Accrington Stanley',
    'Barnet',
    'Barrow',
    'Bristol Rovers',
    'Bromley',
    'Cambridge United',
    'Cheltenham Town',
    'Chesterfield',
    'Colchester United',
    'Crawley Town',
    'Crewe Alexandra',
    'Fleetwood Town',
    'Gillingham',
    'Grimsby Town',
    'Harrogate Town',
    'Milton Keynes Dons',
    'Newport County',
    'Notts County',
    'Oldham Athletic',
    'Salford City',
    'Shrewsbury Town',
    'Swindon Town',
    'Tranmere Rovers',
    'Walsall',
  ],
  "Women's Super League": [
    'Arsenal',
    'Aston Villa',
    'Brighton & Hove Albion',
    'Chelsea',
    'Everton',
    'Leicester City',
    'Liverpool',
    'London City Lionesses',
    'Manchester City',
    'Manchester United',
    'Tottenham Hotspur',
    'West Ham United',
  ],

  // ===== SPAIN =====
  'LaLiga EA Sports': [
    'Alavés',
    'Athletic Club',
    'Atlético de Madrid',
    'Celta de Vigo',
    'Elche',
    'Espanyol',
    'FC Barcelona',
    'Getafe',
    'Girona',
    'Levante',
    'Mallorca',
    'Osasuna',
    'Rayo Vallecano',
    'Real Betis',
    'Real Madrid',
    'Real Oviedo',
    'Real Sociedad',
    'Sevilla',
    'Valencia',
    'Villarreal',
  ],
  'LaLiga Hypermotion': [
    'Albacete',
    'Almería',
    'Andorra',
    'Burgos',
    'Cádiz',
    'Castellón',
    'Ceuta',
    'Córdoba CF',
    'Cultural Leonesa',
    'Deportivo La Coruña',
    'Eibar',
    'Granada',
    'Huesca',
    'Las Palmas',
    'Leganés',
    'Málaga',
    'Mirandés',
    'Racing Santander',
    'Real Sociedad B',
    'Sporting de Gijón',
    'Valladolid',
    'Zaragoza',
  ],
  'Liga F': [
    'Alhama',
    'Athletic Club',
    'Atlético de Madrid',
    'Deportivo Abanca',
    'DUX Logroño',
    'Espanyol',
    'FC Barcelona',
    'Granada',
    'Levante',
    'Levante Las Planas',
    'Madrid CFF',
    'Real Madrid',
    'Real Sociedad',
    'SD Eibar',
    'Sevilla',
    'UDG Tenerife',
  ],

  // ===== GERMANY =====
  'Bundesliga': [
    '1. FC Heidenheim',
    '1. FC Köln',
    '1899 Hoffenheim',
    'Bayer Leverkusen',
    'Bayern Munich',
    'Borussia Dortmund',
    'Borussia Mönchengladbach',
    'Eintracht Frankfurt',
    'FC Augsburg',
    'FC St. Pauli',
    'Hamburger SV',
    'Mainz 05',
    'RB Leipzig',
    'SC Freiburg',
    'Union Berlin',
    'VfB Stuttgart',
    'VfL Wolfsburg',
    'Werder Bremen',
  ],
  '2. Bundesliga': [
    '1. FC Kaiserslautern',
    '1. FC Magdeburg',
    '1. FC Nürnberg',
    'Arminia Bielefeld',
    'Darmstadt 98',
    'Dynamo Dresden',
    'Eintracht Braunschweig',
    'Fortuna Düsseldorf',
    'Greuther Fürth',
    'Hannover 96',
    'Hertha BSC',
    'Holstein Kiel',
    'Karlsruher SC',
    'Preußen Münster',
    'SC Paderborn',
    'Schalke 04',
    'SV Elversberg',
    'VfL Bochum',
  ],
  '3. Liga': [
    '1. FC Saarbrücken',
    '1. FC Schweinfurt',
    'Alemannia Aachen',
    'Energie Cottbus',
    'Erzgebirge Aue',
    'FC Ingolstadt 04',
    'FC Viktoria Köln',
    'Hansa Rostock',
    'Jahn Regensburg',
    'MSV Duisburg',
    'Rot-Weiss Essen',
    'SC Verl',
    'SSV Ulm',
    'SV Waldhof Mannheim',
    'TGS Hoffenheim II',
    'TSV 1860 München',
    'TSV Havelse',
    'VfB Stuttgart II',
    'VfL Osnabrück',
    'Wehen Wiesbaden',
  ],
  'Frauen-Bundesliga': [
    '1. FC Köln',
    '1. FC Nürnberg',
    '1899 Hoffenheim',
    'Bayer Leverkusen',
    'Bayern Munich',
    'Carl Zeiss Jena',
    'Eintracht Frankfurt',
    'Hamburger SV',
    'RB Leipzig',
    'Rot-Weiss Essen',
    'SC Freiburg',
    'Union Berlin',
    'VfL Wolfsburg',
    'Werder Bremen',
  ],

  // ===== FRANCE =====
  'Ligue 1': [
    'Angers SCO',
    'AS Monaco',
    'Auxerre',
    'FC Lorient',
    'FC Metz',
    'FC Nantes',
    'Havre AC',
    'LOSC Lille',
    'OGC Nice',
    'Olympique de Marseille',
    'Olympique Lyonnais',
    'Paris FC',
    'Paris Saint-Germain',
    'Racing Club de Lens',
    'RC Strasbourg Alsace',
    'Stade Brestois 29',
    'Stade Rennais FC',
    'Toulouse FC',
  ],
  'Ligue 2': [
    'Amiens SC',
    'AS Saint-Étienne',
    'Beauleroix FC',
    'Clermont Foot',
    'Dunkerque',
    'En Avant Guingamp',
    'FC Annecy',
    'Grenoble Foot 38',
    'Laval',
    'Le Mans',
    'Montpellier HSC',
    'Nancy',
    'Pau FC',
    'Red Star FC',
    'Rodez Aveyron',
    'SC Bastia',
    'Stade de Reims',
    'Troyes',
  ],
  'Arkema D1': [
    'AS Saint-Étienne',
    'Dijon',
    'Fleury',
    'Le Havre',
    'Montpellier HSC',
    'Nantes',
    'OL Lyonnes',
    'Olympique de Marseille',
    'Paris FC',
    'Paris Saint-Germain',
    'Racing Club de Lens',
    'Strasbourg',
  ],

  // ===== ITALY =====
  'Serie A': [
    'AS Roma',
    'Atalanta',
    'Bologna',
    'Cagliari',
    'Como',
    'Cremonese',
    'Fiorentina',
    'Genoa',
    'Hellas Verona',
    'Inter',
    'Juventus',
    'Lazio',
    'Lecce',
    'Milan',
    'Monza',
    'Napoli',
    'Parma',
    'Pisa',
    'Sassuolo',
    'Torino',
    'Udinese',
  ],
  'Serie BKT': [
    'Avellino',
    'Bari',
    'Carrarese',
    'Catanzaro',
    'Cesena',
    'Empoli',
    'Frosinone',
    'Juve Stabia',
    'Mantova',
    'Modena',
    'Padova',
    'Palermo',
    'Pescara',
    'Reggiana',
    'Sampdoria',
    'Spezia',
    'Südtirol',
    'Venezia',
    'Virtus Entella',
  ],

  // ===== PORTUGAL =====
  'Liga Portugal': [
    'Alverca',
    'Arouca',
    'AVS',
    'Casa Pia',
    'CD Nacional',
    'Estoril',
    'Estrela Amadora',
    'Famalicão',
    'FC Porto',
    'Gil Vicente',
    'Moreirense',
    'Rio Ave',
    'Santa Clara',
    'SL Benfica',
    'Sporting CP',
    'Sporting de Braga',
    'Tondela',
    'Vitória de Guimarães',
  ],

  // ===== NETHERLANDS =====
  'Eredivisie': [
    'Ajax',
    'AZ',
    'Excelsior',
    'FC Utrecht',
    'FC Volendam',
    'Feyenoord',
    'Fortuna Sittard',
    'Go Ahead Eagles',
    'Groningen',
    'Heracles Almelo',
    'NAC Breda',
    'NEC Nijmegen',
    'PEC Zwolle',
    'PSV',
    'SC Heerenveen',
    'Sparta Rotterdam',
    'Telstar',
    'Twente',
  ],

  // ===== BELGIUM =====
  '1A Pro League': [
    'Cercle Brugge',
    'Charleroi',
    'Club Brugge',
    'Dender EH',
    'Genk',
    'Gent',
    'La Louvière',
    'Leuven',
    'Mechelen',
    'R.S.C Anderlecht',
    'Royal Antwerp FC',
    'Sint-Truiden',
    'Standard Liège',
    'Union SG',
    'Westerlo',
    'Zulte Waregem',
  ],

  // ===== SCOTLAND =====
  'Cinch Premiership': [
    'Aberdeen',
    'Celtic',
    'Dundee',
    'Dundee United',
    'Falkirk',
    'Heart of Midlothian',
    'Hibernian',
    'Kilmarnock',
    'Livingston',
    'Motherwell',
    'Rangers',
    'St Mirren',
  ],

  // ===== DENMARK =====
  '3F Superliga': [
    'Aarhus',
    'Brøndby IF',
    'FC København',
    'FC Midtjylland',
    'FC Nordsjælland',
    'Fredericia',
    'OB Odense',
    'Randers FC',
    'Silkeborg IF',
    'SønderjyskE',
    'Vejle Boldklub',
    'Viborg FF',
  ],

  // ===== NORWAY =====
  'Eliteserien': [
    'Bodø/Glimt',
    'Bryne',
    'Fredrikstad',
    'Hamarkameratene',
    'Haugesund',
    'KFUM Oslo',
    'Kristiansund',
    'Molde',
    'Rosenborg',
    'Sandefjord',
    'Sarpsborg 08',
    'SK Brann',
    'Strømsgodset',
    'Tromsø',
    'Vålerenga',
    'Viking',
  ],

  // ===== SWEDEN =====
  'Allsvenskan': [
    'AIK',
    'BK Häcken',
    'Degerfors IF',
    'Djurgårdens IF',
    'GAIS',
    'Halmstads BK',
    'Hammarby IF',
    'IF Brommapojkarna',
    'IF Elfsborg',
    'IFK Göteborg',
    'IFK Norrköping',
    'IFK Värnamo',
    'Kalmar FF',
    'Malmö FF',
    'Mjällby AIF',
    'Östers IF',
  ],

  // ===== POLAND =====
  'PKO Ekstraklasa': [
    'Arka Gdynia',
    'Bruk-Bet Termalica',
    'Cracovia',
    'GKS Katowice',
    'Górnik Zabrze',
    'Jagiellonia Białystok',
    'Korona Kielce',
    'Lech Poznań',
    'Lechia Gdańsk',
    'Legia Warszawa',
    'Motor Lublin',
    'Piast Gliwice',
    'Pogoń Szczecin',
    'Radomiak Radom',
    'Raków Częstochowa',
    'Widzew Łódź',
    'Wisła Płock',
    'Zagłębie Lubin',
  ],

  // ===== ROMANIA =====
  'Superliga': [
    'Argeș Pitești',
    'Botoșani',
    'CFR Cluj',
    'Csíkszereda Ciuc',
    'Dinamo București',
    'Farul Constanța',
    'FCSB',
    'Hermannstadt',
    'Metaloglobus București',
    'Oțelul Galați',
    'Petrolul',
    'Rapid București',
    'Unirea Slobozia',
    'Universitatea Cluj',
    'Universitatea Craiova',
    'UTA Arad',
  ],

  // ===== IRELAND =====
  'SSE Airtricity Premier Division': [
    'Bohemians',
    'Cork City',
    'Derry City',
    'Drogheda',
    'Galway United',
    'Shamrock Rovers',
    'Shelbourne',
    'Sligo Rovers',
    "St Patrick's Athletic",
    'Waterford',
  ],

  // ===== AUSTRIA =====
  'Admiral Bundesliga': [
    'Blau-Weiß',
    'FC Red Bull Salzburg',
    'FK Austria Wien',
    'Grazer AK',
    'LASK',
    'SCR Altach',
    'SK Rapid Wien',
    'SK Sturm Graz',
    'SV Ried',
    'TSV Hartberg',
    'Wolfsberger AC',
    'WSG Tirol',
  ],

  // ===== BRAZIL =====
  'Série A': [
    'Athletico Paranaense',
    'Atlético Mineiro',
    'Bahia',
    'Botafogo',
    'Corinthians',
    'Criciúma',
    'Cruzeiro',
    'Flamengo',
    'Fluminense',
    'Fortaleza',
    'Grêmio',
    'Internacional',
    'Juventude',
    'Palmeiras',
    'Red Bull Bragantino',
    'Santos',
    'São Paulo',
    'Sport',
    'Vasco da Gama',
    'Vitória',
  ],
  'Série B': [
    'ABC',
    'América Mineiro',
    'Avaí',
    'Ceará',
    'Chapecoense',
    'Coritiba',
    'CRB',
    'CSA',
    'Goiás',
    'Guarani',
    'Ituano',
    'Mirassol',
    'Novorizontino',
    'Operário',
    'Paysandu',
    'Ponte Preta',
    'Sampaio Corrêa',
    'Sport Recife',
    'Tombense',
    'Vila Nova',
  ],

  // ===== ARGENTINA =====
  'Liga Profesional': [
    'Aldosivi',
    'Argentinos Juniors',
    'Atlético Tucumán',
    'Banfield',
    'Barracas Central',
    'Belgrano',
    'Boca Juniors',
    'Central Córdoba',
    'Defensa y Justicia',
    'Deportivo Riestra',
    'Estudiantes',
    'Gimnasia',
    'Godoy Cruz',
    'Huracán',
    'Independiente',
    'Independiente Rivadavia',
    'Instituto Córdoba',
    'Lanús',
    "Newell's Old Boys",
    'Platense',
    'Racing Club',
    'River Plate',
    'Rosario Central',
    'San Lorenzo',
    'San Martín',
    'Sarmiento',
    'Talleres',
    'Tigre',
    'Unión',
    'Vélez Sarsfield',
  ],

  // ===== USA / CANADA =====
  'MLS': [
    'Atlanta United',
    'Austin FC',
    'CF Montréal',
    'Charlotte FC',
    'Chicago Fire',
    'Colorado Rapids',
    'Columbus Crew',
    'D.C. United',
    'FC Cincinnati',
    'FC Dallas',
    'Houston Dynamo',
    'Inter Miami',
    'LA Galaxy',
    'LAFC',
    'Minnesota United',
    'Nashville SC',
    'New England Revolution',
    'New York City FC',
    'New York Red Bulls',
    'Orlando City',
    'Philadelphia Union',
    'Portland Timbers',
    'Real Salt Lake',
    'San Diego FC',
    'San Jose Earthquakes',
    'Seattle Sounders',
    'Sporting KC',
    'St. Louis City SC',
    'Toronto FC',
    'Vancouver Whitecaps',
  ],

  // ===== AUSTRALIA / NEW ZEALAND =====
  'A-League': [
    'Adelaide United',
    'Auckland FC',
    'Brisbane Roar',
    'Central Coast Mariners',
    'Macarthur FC',
    'Melbourne City',
    'Melbourne Victory',
    'Newcastle Jets',
    'Perth Glory',
    'Sydney FC',
    'Wellington Phoenix',
    'Western Sydney Wanderers',
    'Western United',
  ],

  // ===== SAUDI ARABIA =====
  'MBS Pro League': [
    'Al Ahli',
    'Al Fayha',
    'Al Hazem',
    'Al Hilal',
    'Al Ittihad',
    'Al Khaleej',
    'Al Kholood',
    'Al Najma',
    'Al Nassr',
    'Al Okhdood',
    'Al Qadsiah',
    'Al Riyadh SC',
    'Al Shabab',
    'Al Taawoun',
    'Al-Fateh',
    'Damac',
    'Ettifaq FC',
    'Neom',
  ],

  // ===== CHINA =====
  'Chinese Super League': [
    'Beijing Sinobo Guoan',
    'Changchun Yatai',
    'Chengdu Rongcheng',
    'Dalian Yingbo',
    'Henan Jianye',
    'Meizhou Hakka',
    'Qingdao Hainiu',
    'Qingdao West Coast',
    'Shandong Luneng Taishan',
    'Shanghai Greenland Shenhua',
    'Shanghai Port',
    'Shenzhen Peng City',
    'Tianjin TEDA',
    'Wuhan Three Towns',
    'Yunnan Yukun',
    'Zhejiang',
  ],

  // ===== INDIA =====
  'Hero ISL': [
    'ATK Mohun Bagan',
    'Bengaluru',
    'Chennaiyin',
    'East Bengal',
    'Goa',
    'Hyderabad',
    'Jamshedpur',
    'Kerala Blasters',
    'Mohammedan',
    'Mumbai City',
    'NorthEast United',
    'Odisha',
    'RoundGlass Punjab',
    'United Tigers',
  ],

  // ===== SOUTH KOREA =====
  'K-League 1': [
    'Daegu FC',
    'Daejeon Hana Citizen',
    'FC Anyang',
    'FC Seoul',
    'Gangwon FC',
    'Gimcheon Sangmu',
    'Gwangju FC',
    'Jeonbuk Hyundai Motors',
    'Jeju United',
    'Pohang Steelers',
    'Suwon FC',
    'Ulsan Hyundai',
  ],
  'K-League 2': [
    'Ansan Greeners',
    'Bucheon FC 1995',
    'Busan IPark',
    'Cheonan City',
    'Chungbuk Cheongju',
    'Chungnam Asan',
    'FC Anyang',
    'Gimcheon Sangmu',
    'Gimpo FC',
    'Gyeongnam FC',
    'Jeonnam Dragons',
    'Seongnam FC',
    'Seoul E-Land',
  ],

  // ===== NO LICENSED LEAGUE =====
  'No League': [
    'Adidas All-Star',
    'AEK Athens',
    'AFC Richmond',
    'Al Ahly',
    'Al Ain FC',
    'APOEL FC',
    'Atlético Nacional',
    'Dinamo Kiev',
    'Dinamo Zagreb',
    'Ferencváros TC',
    'Hajduk Split',
    'HJK Helsinki',
    'Kaizer Chiefs',
    'Mamelodi Sundowns',
    'MLS All-Star',
    'Olympiacos',
    'Orlando Pirates',
    'Panathinaikos',
    'PAOK',
    'Shakhtar Donetsk',
    'Slavia Praha',
    'Soccer Aid',
    'Sparta Praha',
    'Viktoria Plzeň',
  ],
};

export const LEAGUE_NAMES = Object.keys(CLUBS_BY_LEAGUE);

export const ALL_CLUBS = Object.values(CLUBS_BY_LEAGUE).flat();
