export const CLUBS_BY_LEAGUE: Record<string, string[]> = {
  'Premier League': [
    'AFC Bournemouth',
    'Arsenal',
    'Aston Villa',
    'Brentford',
    'Brighton & Hove Albion',
    'Burnley',
    'Chelsea',
    'Crystal Palace',
    'Everton',
    'Fulham',
    'Leeds United',
    'Liverpool',
    'Manchester City',
    'Manchester United',
    'Newcastle United',
    'Nottingham Forest',
    'Sunderland',
    'Tottenham Hotspur',
    'West Ham United',
    'Wolverhampton Wanderers',
  ],
  'La Liga': [
    'Athletic Club',
    'Atlético de Madrid',
    'Barcelona',
    'Celta de Vigo',
    'Deportivo Alavés',
    'Elche',
    'Espanyol',
    'Getafe',
    'Girona',
    'Las Palmas',
    'Leganés',
    'Levante',
    'Mallorca',
    'Osasuna',
    'Rayo Vallecano',
    'Real Betis',
    'Real Madrid',
    'Real Oviedo',
    'Real Sociedad',
    'Sevilla',
    'Valencia',
    'Villarreal',
  ],
  'Bundesliga': [
    'Augsburg',
    'Bayer Leverkusen',
    'Bayern de Munique',
    'Borussia Dortmund',
    'Borussia Mönchengladbach',
    'Eintracht Frankfurt',
    'Freiburg',
    'Hamburger SV',
    'Heidenheim',
    'Hoffenheim',
    'Holstein Kiel',
    'Köln',
    'Mainz 05',
    'RB Leipzig',
    'St. Pauli',
    'Stuttgart',
    'Union Berlin',
    'Werder Bremen',
    'Wolfsburg',
  ],
  'Serie A': [
    'Atalanta',
    'Bologna',
    'Cagliari',
    'Como',
    'Cremonese',
    'Empoli',
    'Fiorentina',
    'Genoa',
    'Hellas Verona',
    'Inter de Milão',
    'Juventus',
    'Lazio',
    'Lecce',
    'Milan',
    'Monza',
    'Napoli',
    'Parma',
    'Pisa',
    'Roma',
    'Torino',
    'Udinese',
    'Venezia',
  ],
  'Ligue 1': [
    'Angers',
    'Auxerre',
    'Brest',
    'Havre AC',
    'Lens',
    'Lille',
    'Lorient',
    'Metz',
    'Monaco',
    'Montpellier',
    'Nantes',
    'Nice',
    'Olympique de Marseille',
    'Olympique Lyonnais',
    'Paris FC',
    'Paris Saint-Germain',
    'Reims',
    'Rennes',
    'Saint-Étienne',
    'Strasbourg',
    'Toulouse',
  ],
};
